Привет Даниил! Всегда рад, когда мою работу проверяешь именно ты, спасибо тебе за дельные наставления и приятные слова!
По поводу твоих комментариев:
1. Ты сказал добавить проверку допустимого значения k (количество рекоммендаций) для онлайн-рекомендаций, однако в коде это выполнено срезом по списку и даже если пользователь задаст больше имеющегося числа взаимодействий - ошибку это не выдаст, просто выдаст возможный максимум - нужно ли в этом случае делать проверку?
2. Ты также говорил добавить валидацию данных для similar_items, а именно наличие столбца "item_id_2". Я думал сделать это через assert, но это никак не спасет сервер от падения, тогда вернулся try except, но даже если я обработаю эту ошибку - это база данных сервера и если в ней отсутствует один из необходимых для рекомендаций столбец - то, что выдавать пользователю в принципе? А проверка на "item_id_1" там есть.
3. Спасибо, что заметил - "type" действительно зарезервированное имя, данная ошибка встречается и в курсе, если это важно.
4. Вынес отдельно url серверов в файл constants.py, возник вопрос: как сделать, чтобы импорт работал независимо от того из какой директории ты запускаешь код - только писать полный путь до файла в импорте? 
Сейчас, чтобы не возникло ошибки, необходимо запускать сервер находясь в папке с файлом constants.py.
5. Не смог найти название ошибки, которая возникает при неправильном обращении к серверу)
ConnectionError и  ConnectionRefusedError не подошли, а NewConnectionError системе не знакомо, пришлось писать просто except.

Заранее благодарю тебя!
